### ISSUE TITLE
broadcasts.yml is being overwritten on reload

### ISSUE THREAD

**Issue by paulhlschr** [Wiicart/Strings#15]
### Issue
When reloading Strings or restarting the server, any non-default keys in `broadcasts.yml` are overwritten, therefore deleting all custom broadcasts. Changes of already existing keys are being saved.

### How to reproduce:

1. Install Strings.
2. Add new broadcasts with custom names (e.g. `shops`).
3. Reload Strings via `/strings reload`

### Server Information
- Strings Version: 1.4
- Minecraft Version: 1.21.3
- Server Software: Paper 1.21.3-82

#### Pre-Reload
```
broadcasts:
  shops:
    - ''
    - '&e&lErstelle deinen eigenen Shop!'
    - '&7Mit &c/ds buy &7kannst du für nur &aE25 &7deinen eigenen Laden eröffnen.'
    - ''
  discord:
    - ''
    - '&e&lDu hast Fragen, Feedback oder Probleme im Spiel?'
    - '&7Schreibe uns ganz einfach in &3#minecraft &7auf unserem &3Discord&7-Server!'
    - ''
```
#### Post-Reload
```
broadcasts:
  discord:
    - ''
    - '&e&lDu hast Fragen, Feedback oder Probleme im Spiel?'
    - '&7Schreibe uns ganz einfach in &3#minecraft &7auf unserem &3Discord&7-Server!'
    - ''
```
